FROM php:8.4-cli

RUN apt-get update -qq \
    && apt-get install -y -qq git unzip > /dev/null 2>&1 \
    && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-install pcntl > /dev/null 2>&1 \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer > /dev/null 2>&1

WORKDIR /app
